# Generated by Django 3.1.4 on 2021-03-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed',
            field=models.IntegerField(default=0),
        ),
    ]
